version: "3.9"



########################### NETWORKS
networks:
  web:
    name: web
    driver: bridge
    external: true
    attachable: true

########################### SERVICES
services:
  ########################### APP
  planejamento:
    image: thassiamorim/planejamento
    container_name: planejamento
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - web
    

